# Generated by Django 4.2.10 on 2024-02-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
