# Generated by Django 5.0 on 2024-02-11 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.IntegerField(default=0)),
                ('invoice_no', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('invoice_img', models.ImageField(upload_to='')),
                ('buying_time', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
