# Generated by Django 4.2.6 on 2023-10-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_reg_login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="highest_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_condition",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
