# Generated by Django 4.2.10 on 2024-02-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_login', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
