# Generated by Django 4.2.10 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_login', '0002_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='buyer_nrc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transition',
            name='buyer_ph',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transition',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transition',
            name='invoice_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='transition',
            name='invoice_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
