# Generated by Django 4.2.10 on 2024-02-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_login', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
